apiVersion: v1
kind: Service
metadata:
  labels:
    app: csharp-ui
    tier: Service
  name: csharp-ui
  namespace: org-services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: csharp-ui
  sessionAffinity: None
  type: ClusterIP
